---
DEFAULT_JIRA_ADDITIONAL_LABELS: '["4.19-lp","self-managed-lp"]'
DEFAULT_JIRA_PROJECT: LPINTEROP
rules_config_path: https://raw.githubusercontent.com/CSPI-QE/cspi-utils/main/firewatch-base-configs/aws-ipi/lp-interop.json
fail_with_test_failure: "true"
jira_transition_map:
  LPINTEROP: PASS
  CSPIT: PASS
  OCSQE: DONE
  DEFAULT: CLOSED

